class MtoCompareRow:
    column_list = {
        UNITS,
        CODE,
        TAGS,
        VALUES,
        VENDOR,
        MASS,
        ANNOTATION,
        NUMBERS,
        NOMENCLATURE,
        TYPE_MARK,
        NAME,
        PROHIBITION,
        REPLACEMENT,
        EQUIPMENT_CODE,
        ROW_TYPE,
        TITLE,
        SPECIFICATION_NAME,
        G_BASE_CABLE_LAYING_FLAG,
        G_BASE_CABLE_LAYING_TYPE,
        G_BASE_CABLE_LAYING_VARIANTS,
        G_BASE_CABLE_SUMMARY_VARIANTS,
    }