from base.tables_columns import *


class Dbf:
    wireName = "wireName"
    Name = "Name"
    ShortName = "ShortName"

    id = "id"

    Description = "Description"
    SpecDescription = "SpecDescription"
    # SpecСomment = "SpecСomment"
    DbSpecDescription = "DbSpecDescription"
    # markName = "markName"
    Code = "Code"
    DbCode = "DbCode"
    Manufacturer = "Manufacturer"
    mfrId = "mfrId"
    MeashureUnits = "MeashureUnits"
    Mass = "Mass"
    mass = "mass"


temp_def = {
    BD_ID: Dbf,
    CODE: Dbf,
    NAME: Dbf,
    TYPE_MARK: Dbf,
    VENDOR: Dbf,
    MASS: Dbf,
    UNITS: Dbf
}

table_fields = {
    "AirBleeder": {},
    "Bath": {},
    "Bidet": {},
    "Bolt": {},
    "Boss": {},
    "BranchPipe": {},
    "CaeMaterialUtility": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
        UNITS: Dbf.MeashureUnits
    },
    "Cleaning": {},
    "ClimateTable": {},
    "CompensatingSocket": {},
    "CondensateDrain": {},
    "Cross": {},
    "CrossBiplanar": {},
    "DbCableCanalPartition": {},
    "DbCaeMaterialUtilitySet": {},
    "DbCcMountSystem": {},
    "DbDwgFiles": {},
    "DbElBoardUtilitySet": {},
    "DbElCSwitch": {},
    "DbElFiderUtilitySet": {},
    "DbElLightUtilitySet": {},
    "DbElSocket": {},
    "DbElSocketUtilitySet": {},
    "DbElSwitch": {},
    "DbElUzdp": {},
    "DbGcMountSystem": {},
    "DbGraphic": {},
    "DbHeater": {},
    "DbImages": {},
    "DbLtKiTable": {},
    "DbOpsBox": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbOpsBox_DbDwgSchemaList_DbDwgFiles": {},
    "DbOpsCameraAccessories": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.Name,
        TYPE_MARK: Dbf.ShortName
    },
    "DbOpsDeviceType": {},
    "DbOpsObjectiveLens": {},
    "DbOpsReservePowerSupply": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbOpsReservePowerSupply_DbDwgSchemaList_DbDwgFiles": {},
    "DbOpsSoundAmplifier": {},
    "DbOpsStorageBattery": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbOpsVideoDevices": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbOpsVideoDevices_DbDwgSchemaList_DbDwgFiles": {},
    "DbOpsVideoMatrixParameters": {},
    "DbPipeCoefficientOfLocalResistance": {},
    "DbPipePreassureLoss": {},
    "DbScsGcAccessoryUnit": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbScsGcBoltingAccessoryUnits": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbScsGcCoverUnit": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbScsGcSeriaConfigiration": {},
    "DbScsGutterCover": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbScsGutterPartition": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbScsGutterUtilitySet": {},
    "DbScsPanelUtilitySet": {},
    "DbScsShellUtilitySet": {},
    "DbScsTubeSeriaConfigiration": {},
    "DbSecurityCamera": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbSecurityCamera_DbDwgSchemaList_DbDwgFiles": {},
    "DbSpecEquipment": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.Name,
        TYPE_MARK: Dbf.ShortName,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "DbTbMountSystem": {
    },
    "DbTowelDryer": {},
    "DcCableCanalCover": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    # Пустая таблица - сделано на всякий случай
    "DeviceComponent": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    # Пустая таблица - сделано на всякий случай
    "DrainageHopper": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    # Пустая таблица - сделано на всякий случай
    "DrinkingFountain": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    # Пустая таблица - сделано на всякий случай
    "DSInformation": {
    },
    # Пустая таблица - сделано на всякий случай
    "ElAmperemeter": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    # Пустая таблица - сделано на всякий случай
    "ElAutomat": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    # Пустая таблица - сделано на всякий случай
    "ElBlock": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    # Пустая таблица - сделано на всякий случай
    "ElBlockBoard": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass
    },
    "ElBoard": {},
    "ElBoardUtility": {},
    "Elbow": {},
    "ElBox": {},
    "ElCasing": {},
    "ElCompensatorReactivePower": {},
    "ElControlCabel": {},
    "ElControlDevice": {},
    "ElControlWireMark": {},
    "ElCounter": {},
    "ElCurrentTransformer": {},
    "ElDbCase": {},
    "ElDbComplex": {},
    "ElDbEngine": {},
    "ElDbHeater": {},
    "ElDistPanel": {},
    "ElFider": {},
    "ElFiderUtilities": {},
    "ElFrequenceTransformer": {},
    "ElInputAprBoard": {},
    "ElInputBusBoard": {},
    "ElKnifeSwitch": {},
    "ElLamp": {},
    "ElLighting": {},
    "ElLightUtility": {},
    "ElModuleBoard": {},
    "ElOvervoltageSuppressor": {},
    "ElPushButtonStation": {},
    "ElRailBoard": {},
    "ElResistReactor": {},
    "ElSafeDevice": {},
    "ElShieldingUnit": {},
    "ElSocketUtility": {},
    "ElStandartDistrBoard": {},
    "ElStarter": {},
    "ElTransformer": {},
    "ElUzo": {},
    "ElVoltmeter": {},
    'ElWire': {
        BD_ID: Dbf.id,
        CODE: Dbf.DbCode,
        NAME: Dbf.DbSpecDescription,
        TYPE_MARK: Dbf.wireName,
        VENDOR: Dbf.mfrId,
        MASS: Dbf.mass,
        },
    "ElWireConductMaterial": {},
    "ElWireIsolationMaterial": {},
    "ElWireMark": {
        # BD_ID: Dbf.id,
        # CODE: Dbf.DbCode,
        # NAME: Dbf.SpecСomment,
        # TYPE_MARK: Dbf.markName,
        # VENDOR: Dbf.mfrId,
        # MASS: Dbf.mass,
    },
    "ExplodeSafeLevel": {},
    "FieldOldValue": {},
    "FireCock": {},
    "FireProofCableSystem": {},
    "Flange": {},
    "FloorCup": {},
    "Funnel": {},
    "Gag": {},
    "HeadRegulator": {},
    "HeatMeter": {},
    "Hydrant": {},
    "ImportConflictField": {},
    "ImportObjectStatus": {},
    "Insulation": {},
    "Manometer": {},
    "Mixer": {},
    "Muff": {},
    "OpsBusEndDevice": {},
    "OpsBusEndDevice_DbDwgSchemaList_DbDwgFiles": {},
    "OpsCommutationDevice": {},
    "OpsCommutationDevice_DbDwgSchemaList_DbDwgFiles": {},
    "OpsControlAndOperationDevice": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsControlAndOperationDevice_DbDwgSchemaList_DbDwgFiles": {},
    "OpsControlDevice": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsControlDevice_DbDwgSchemaList_DbDwgFiles": {},
    "OpsControlDevice_DbSlotSockets_OpsSlotSocket": {},
    "OpsController": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsController_DbDwgSchemaList_DbDwgFiles": {},
    "OpsController_DbSlotSockets_OpsSlotSocket": {},
    "OpsExecutiveDevice": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsExecutiveDevice_DbDwgSchemaList_DbDwgFiles": {},
    "OpsFirePointSensor": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsFirePointSensor_DbDwgSchemaList_DbDwgFiles": {},
    "OpsFireSensorBase": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsGuardAnnunciator": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsGuardAnnunciator_DbDwgSchemaList_DbDwgFiles": {},
    "OpsInterfaceType": {},
    "OpsLinearSensor": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsLinearSensor_DbDwgSchemaList_DbDwgFiles": {},
    "OpsNotifier": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsNotifier_DbDwgSchemaList_DbDwgFiles": {},
    "OpsShell": {},
    "OpsShortCircuitProtectionDevice": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsShortCircuitProtectionDevice_DbDwgSchemaList_DbDwgFiles": {},
    "OpsSlotSocket": {},
    "OpsSystemControlAccessDevice": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "OpsSystemControlAccessDevice_DbDwgSchemaList_DbDwgFiles": {},
    "Orifice": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        # TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "Pan": {},
    "Pipe": {},
    "ProtectionSleeve": {},
    "Pump": {},
    "Revision": {},
    "SafeDegree": {},
    "ScsCabelCanal": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsCableCanalSupplement": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsCableFitting": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsCableSystemType": {},
    "ScsCord": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        # TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsGcFitting": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsGutterBolting": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsGutterCanal": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsGutterSupplement": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        # NAME: Dbf.SpecDescription,
        # TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsOrganaizerPanel": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsPanelUtilityUnit": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsPipe": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsShellDistr": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsShellUtility": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "ScsTubeFitting": {
        BD_ID: Dbf.id,
        CODE: Dbf.Code,
        NAME: Dbf.SpecDescription,
        TYPE_MARK: Dbf.Name,
        VENDOR: Dbf.Manufacturer,
        MASS: Dbf.Mass,
    },
    "Shower": {},
    "ShowerPan": {},
    "Sink": {},
    "Sump": {},
    "Tap": {},
    "Tee": {},
    "Thermomanometer": {},
    "Thermometer": {},
    "Trap": {},
    "Urinal": {},
    "Valve": {},
    "WashBowl": {},
    "WashStand": {},
    "WaterGauge": {},
    "WateringTap": {},

}
