from cable_mapping.constants import *


class ColumnsCableTable:
    main_list = (
        CJ_CABLE_CODE,
        CJ_CABLE_NUMBER,
        CJ_ADDITIONAL_CODE,
        CJ_CABLE_LABEL,
        CJ_CABLE_FULL_TAG,

        CJ_FROM,
        CJ_FROM_TERMINAL,
        CJ_WHERE,
        CJ_WHERE_TERMINAL,
        CJ_CABLE_MARK,
        CABLE_LAYING_IN_CABIN,
        CABLE_LAYING_IN_TRAY,
        CABLE_LAYING_IN_CABLE_CHANEL,
        CABLE_LAYING_IN_OPEN,
        CABLE_LAYING_IN_FLUTED,
        CABLE_LAYING_IN_METAL_HOUSE,
        CABLE_LAYING_IN_TUBE,
        CABLE_LAYING_IN_TRENCH,

        CJ_TOTAL_LENGTH,
        CJ_ANNOTAION,

        TPK_R0_CABLE,
        TPK_R2_FROM_FLOOR,
        TPK_R3_FROM_ROOM,
        TPK_R5_WHERE_FLOOR,
        TPK_R6_WHERE_ROOM,
        TPK_R8_TOTAL_LENGTH,
        TPK_R9_CABLE_LAYING_TYPE,
        TPK_R10_CABLE_LAYING_LENGTH,
        CJ_SYSTEM,
        CJ_CABLE_CODE_FLAG,
    )
    cj_list_extend = (
        CJ_SYSTEM,
        CJ_CABLE_CODE,
        CJ_CABLE_NUMBER,
        CJ_CABLE_CODE_FLAG,
        CJ_ADDITIONAL_CODE,
        CJ_CABLE_LABEL,
        CJ_CABLE_FULL_TAG,
        CJ_FROM,
        CJ_FROM_TERMINAL,
        CJ_WHERE,
        CJ_WHERE_TERMINAL,
        CJ_CABLE_MARK,
        CABLE_LAYING_IN_CABIN,
        CABLE_LAYING_IN_TRAY,
        CABLE_LAYING_IN_CABLE_CHANEL,
        CABLE_LAYING_IN_OPEN,
        CABLE_LAYING_IN_FLUTED,
        CABLE_LAYING_IN_METAL_HOUSE,
        CABLE_LAYING_IN_TUBE,
        CABLE_LAYING_IN_TRENCH,
        CJ_TOTAL_LENGTH,
        CJ_ANNOTAION
    )
    tpk_normalized_list = (
        TPK_R0_CABLE,
        CJ_FROM,
        CJ_FROM_TERMINAL,
        CJ_WHERE,
        CJ_WHERE_TERMINAL,
        TPK_R2_FROM_FLOOR,
        TPK_R3_FROM_ROOM,
        TPK_R5_WHERE_FLOOR,
        TPK_R6_WHERE_ROOM,
        CJ_CABLE_MARK,
        TPK_R8_TOTAL_LENGTH,
        CABLE_LAYING_IN_CABIN,
        CABLE_LAYING_IN_TRAY,
        CABLE_LAYING_IN_CABLE_CHANEL,
        CABLE_LAYING_IN_OPEN,
        CABLE_LAYING_IN_FLUTED,
        CABLE_LAYING_IN_METAL_HOUSE,
        CABLE_LAYING_IN_TUBE,
        CABLE_LAYING_IN_TRENCH,
        CJ_TOTAL_LENGTH,
        CJ_ANNOTAION,
    )
    cj_list = (
        CJ_CABLE_LABEL,
        CJ_CABLE_FULL_TAG,
        CJ_FROM,
        CJ_FROM_TERMINAL,
        CJ_WHERE,
        CJ_WHERE_TERMINAL,
        CJ_CABLE_MARK,
        CABLE_LAYING_IN_CABIN,
        CABLE_LAYING_IN_TRAY,
        CABLE_LAYING_IN_CABLE_CHANEL,
        CABLE_LAYING_IN_OPEN,
        CABLE_LAYING_IN_FLUTED,
        CABLE_LAYING_IN_METAL_HOUSE,
        CABLE_LAYING_IN_TUBE,
        CABLE_LAYING_IN_TRENCH,
        CJ_TOTAL_LENGTH,
        CJ_ANNOTAION
    )

    class TPK:
        column_dict = {
            0: TPK_R0_CABLE,
            1: CJ_FROM,
            2: TPK_R2_FROM_FLOOR,
            3: TPK_R3_FROM_ROOM,
            4: CJ_WHERE,
            5: TPK_R5_WHERE_FLOOR,
            6: TPK_R6_WHERE_ROOM,
            7: CJ_CABLE_MARK,
            8: TPK_R8_TOTAL_LENGTH,
            9: TPK_R9_CABLE_LAYING_TYPE,
            10: TPK_R10_CABLE_LAYING_LENGTH,
        }

    class CJ:
        column_dict = {
            0: CJ_CABLE_LABEL,
            1: CJ_CABLE_FULL_TAG,
            2: CJ_FROM,
            3: CJ_FROM_TERMINAL,
            4: CJ_WHERE,
            5: CJ_WHERE_TERMINAL,
            6: CJ_CABLE_MARK,
            7: CABLE_LAYING_IN_CABIN,
            8: CABLE_LAYING_IN_CABIN,
            9: CABLE_LAYING_IN_TRAY,
            10: CABLE_LAYING_IN_CABLE_CHANEL,
            11: CABLE_LAYING_IN_OPEN,
            12: CABLE_LAYING_IN_FLUTED,
            13: CABLE_LAYING_IN_METAL_HOUSE,
            14: CABLE_LAYING_IN_TUBE,
            15: CJ_TOTAL_LENGTH,
            16: CJ_ANNOTAION,
        }
